name: Deploy to S3

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI with credentials from GitHub secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update this to match your bucket's region

      # Step 3: List current contents in S3 bucket for debugging purposes
      - name: List files in S3 bucket
        run: aws s3 ls s3://diceware-github-actions

      # Step 4: Sync files to S3 (excluding .git folder)
      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://diceware-github-actions --exclude ".git/*"

